# Generated by Django 4.2.27 on 2026-01-12 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Kenyan phone number (07xxxxxxxx or 01xxxxxxxx)', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '07xxxxxxxx' or '01xxxxxxxx'", regex='^(07|01)\\d{8}$')])),
                ('amount_won', models.DecimalField(decimal_places=2, help_text='Amount won by the user', max_digits=10)),
                ('session_id', models.CharField(help_text='Session ID to track user', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of withdrawal request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='wheel_spin__created_a1b427_idx'), models.Index(fields=['status'], name='wheel_spin__status_9b507f_idx'), models.Index(fields=['phone_number'], name='wheel_spin__phone_n_299098_idx')],
            },
        ),
    ]
